<?php

namespace Wabbox\LettreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PersonneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonneRepository extends EntityRepository
{
    public function getPersonneUser($expediteur, $id)
    {
         $qb = $this->createQueryBuilder('p')
                    ->leftJoin('p.user', 'u')
                    ->addSelect('u');

        $qb  ->where('u.id = :id')
             ->setParameter('id', $id)
             ->andWhere('p.expediteur = :expediteur')
             ->setParameter('expediteur', $expediteur);

        return $qb->getQuery()
                   ->getResult();
    }

    public function getExpediteur($id)
    {
         $qb = $this->createQueryBuilder('p')
                    ->leftJoin('p.user', 'u')
                    ->addSelect('u');

        $qb  ->where('u.id = :id')
             ->setParameter('id', $id)
             ->andWhere('p.expediteur = :expediteur')
             ->setParameter('expediteur', true);

        return $qb->getQuery()
                   ->getSingleResult();
    }
}
