imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: "%kernel.debug%"
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trust_proxy_headers: false # Deprecated in 2.0; will be removed in 2.3 (used trusted_proxies instead)
    trusted_proxies: ~
    session:         ~

# Fos_user
fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    # Permet de renseigner la nouvelle entity utilisateur
    user_class: Wabbox\UserBundle\Entity\User

    from_email:
            address:        perrin.gontran@gmail.com
            sender_name:    Perrin Gontran

    registration:
        confirmation:
            enabled:    true
        form:
            type:       wabbox_user_registration

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

#parameters:
#    assetic.filter.compass.images_dir: %kernel.root_dir%/../web/img
#    assetic.filter.compass.http_path:  /img


# Assetic Configuration
#assetic:
#    debug:          "%kernel.debug%"
#    use_controller: false
#    bundles:        [ ]
#    #java: /usr/bin/java
#    filters:
#        cssrewrite: ~
#        closure:
#            jar: "%kernel.root_dir%/Resources/java/compiler.jar"
#        yui_css:
#            jar: "%kernel.root_dir%/Resources/java/yuicompressor.jar"
#        yui_js:
#            jar: "%kernel.root_dir%/Resources/java/yuicompressor.jar"


assetic:
    debug:                "%kernel.debug%"
    use_controller:
        enabled:              "%kernel.debug%"
        profiler:             false
    #read_from:            "%kernel.root_dir%/../web"
    #write_to:             "%assetic.read_from%"
    filters:
        cssrewrite: ~
        compass:
            bin:     "C:/Ruby193/bin/compass"
            plugins: ['zurb-foundation']
            #apply_to: "/\.s[ac]ss$/"
            apply_to: "\.scss$"
        yui_css:
            jar:     "%kernel.root_dir%/Resources/java/yuicompressor.jar"
            apply_to: "\.css$"
        yui_js:
            jar:     "%kernel.root_dir%/Resources/java/yuicompressor.jar"
            apply_to: "\.js$"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
